version: "3"
#name and ports must be in quotes
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: "minecraft"
    environment:
      EULA: 1
      MEMORY: 4G
      VERSION: 1.19.2
    ports:
      - "25568:25565"
    volumes:
      - "./:/data"
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
